#!/usr/bin/env ruby
require 'git'
require 'optparse'
require 'terminal-announce'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: git-sync --from <git-repo> --to <local-path>"
  opts.on("--from REPO", "Git repository to sync.") do |repo|
    options[:repo] = repo
  end
  opts.on("--to PATH", "Local path to clone or pull into.") do |path|
    options[:path] = path
  end
end.parse!

p options

raise "Invalid git repository: #{options[:repo]}" unless options[:repo] =~ /.git/

if Dir.exist? options[:path]
  Announce.info "Pulling repository at #{File.expand_path options[:path]}"
  git = Git.open options[:path]
  puts git.pull
else
  Announce.info "Cloning repository to #{File.expand_path options[:path]}"
  directory, path = File.basename(options[:path]), File.dirname(options[:path])
  Git.clone options[:repo], directory, path: path
end
