#!/usr/bin/env ruby
require 'git'
require 'optparse'
require 'terminal-announce'

OptionParser.new do |opts|
  opts.banner = "Usage: git-sync <repo> [path]"
end.parse!

repo = ARGV[0]
raise "Invalid git repository: #{repo}" unless repo =~ /.git/
path = ARGV[1] || "#{Dir.pwd}/#{File.basename repo, '.git'}"
path = File.expand_path path

if Dir.exist? "#{path}/.git"
  Announce.info "Pulling repository at #{path}"
  git = Git.open path
  puts git.pull
else
  Announce.info "Cloning repository to #{path}"
  directory, path = File.basename(path), File.dirname(path)
  Git.clone repo, directory, path: path
end
